version: '3.8'

services:
  users_db:
    container_name: users-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=user_todos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
    
    ports:
      - 15432:5432

      